/**
 * generated-api.ts — short ergonomic aliases over the auto-generated types.
 *
 * `generated.types.ts` (auto-generated by openapi-typescript) exposes every
 * schema through the awkward indexed type `components['schemas']['CustomerDto']`.
 * Re-exporting short names here gives us:
 *   - readable call sites: `ServerCustomer` instead of `components['schemas']['CustomerDto']`
 *   - a single spot to widen / narrow a server type when the generated shape
 *     is too permissive (e.g. the `id` field comes back as `id?: number` but
 *     is always present on responses)
 *
 * NEVER edit generated.types.ts by hand — rerun `npm run gen:api-types`
 * after refreshing the OpenAPI snapshot (`npm run gen:openapi-snapshot`).
 * `npm run verify:api-types` in CI catches drift between snapshot and types.
 *
 * Design note — why we don't also replace the hand-written Customer, Page,
 * etc. interfaces in api.service.ts with these aliases:
 *   1. The hand-written interfaces document behaviour (cache hints, null
 *      semantics, the v1-vs-v2 `createdAt` nuance) that the OpenAPI spec
 *      doesn't capture fully.
 *   2. A full replacement is a bigger refactor with no compile-time win —
 *      we get the contract guarantee simply by cross-checking the two via
 *      {@link assertCompatible} below.
 * See docs/how-to/openapi-types-generation.md for the full rationale.
 */
import type { components } from './generated.types';

/** Server DTO for `GET /customers/{id}` — auto-generated from OpenAPI. */
export type ServerCustomer = components['schemas']['CustomerDto'];

/** Server DTO for `POST /customers` request body — auto-generated. */
export type ServerCreateCustomerRequest = components['schemas']['CreateCustomerRequest'];

/** Server DTO for `PATCH /customers/{id}` — all fields optional. */
export type ServerPatchCustomerRequest = components['schemas']['PatchCustomerRequest'];

/** Server DTO for `GET /customers/summary`. */
export type ServerCustomerSummary = components['schemas']['CustomerSummary'];

/** Server DTO for `GET /customers/aggregate` — virtual-threads demo. */
export type ServerAggregatedResponse = components['schemas']['AggregatedResponse'];

/** Server DTO for `POST /auth/login` request body. */
export type ServerLoginRequest = components['schemas']['LoginRequest'];

/**
 * Compile-time shape-compatibility check between two types.
 *
 * Returns `true` (at the type level) iff `A` is assignable to `B` AND `B`
 * is assignable to `A` — in other words, the two types describe the same
 * required-field surface. Used at the bottom of api.service.ts to statically
 * confirm that our hand-written Customer-family interfaces stay aligned
 * with the server-generated ones.
 *
 * If the server adds a required field (say `phone`), the static assertion
 * will fail at tsc time with a readable error pointing at the DTO pair,
 * not at a runtime 500 much later.
 */
export type AssertCompatible<A, B> = [A] extends [B] ? ([B] extends [A] ? true : never) : never;
