/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/customers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a customer by ID
     * @description Returns one customer by primary key. Read-only; uses the JPA second-level Caffeine cache (`@Cacheable("customers")`). Returns 404 if the ID does not exist.
     */
    get: operations['getById'];
    /**
     * Update a customer
     * @description Replaces the name and email of an existing customer. Requires ROLE_USER or ROLE_ADMIN.
     */
    put: operations['update'];
    post?: never;
    /**
     * Delete a customer
     * @description Permanently deletes the customer. Requires ROLE_ADMIN.
     */
    delete: operations['delete'];
    options?: never;
    head?: never;
    /**
     * Partially update a customer
     * @description Applies only the provided fields. Omit fields you do not want to change. Requires ROLE_USER or ROLE_ADMIN.
     */
    patch: operations['patch'];
    trace?: never;
  };
  '/customers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List customers (v1)
     * @description Paginated list of customers (id, name, email). Default version — also returned when `X-API-Version` header is absent. Supports optional full-text search on name and email. Adds RFC 8288 `Link` headers (next, prev, first, last) and `Deprecation`/`Sunset` headers.
     */
    get: operations['getAllV2'];
    put?: never;
    /**
     * Create a customer
     * @description Creates a new customer, fires a Kafka `CustomerCreatedEvent` (fire-and-forget), adds the customer to the in-memory recent buffer, and increments the `customer.created.count` Micrometer counter. Requires `ROLE_ADMIN`. Supports idempotency via the `Idempotency-Key` header — repeating the same request returns the cached response.
     */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/batch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Batch import customers
     * @description Creates multiple customers in one request. Each entry is validated individually — a failure on one row does not abort the batch. Returns a summary with `created`, `failed`, and `errors` lists. Requires ROLE_USER or ROLE_ADMIN.
     */
    post: operations['batchCreate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chaos/{experiment}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger a chaos experiment */
    post: operations['trigger'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh tokens
     * @description Rotates the refresh token and returns a new access + refresh pair. The old refresh token is consumed (single-use) to prevent replay attacks.
     */
    post: operations['refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout — invalidate access and refresh tokens
     * @description Blacklists the current JWT (stored in Redis until expiry) and deletes all refresh tokens. Requires a valid Bearer token in the Authorization header.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login — obtain access + refresh tokens
     * @description Validates credentials and returns a signed JWT pair. Demo accounts: `admin/admin` (ROLE_ADMIN — full access), `user/user` (ROLE_USER — read + write), `viewer/viewer` (ROLE_READER — read-only). Brute-force protection: after 5 failed attempts the IP is locked out for 15 minutes. Copy the `accessToken` and use it in the **Authorize** button above.
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scheduled/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List ShedLock-tracked scheduled jobs
     * @description Returns one entry per scheduled job registered with ShedLock, including the last lock holder + lock-until timestamp. Useful to verify that scheduled tasks are not silently failing or deadlocked across replicas. Read-only; queries the `shedlock` table directly via JdbcTemplate.
     */
    get: operations['getJobs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/diag/startup-timings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Startup timings
     * @description Returns the total boot duration plus per-bean init cost (≥ 5 ms). Useful to explain what happened during the first few seconds of the Spring Boot startup — Flyway, Kafka listener registration, circuit-breaker wiring, OpenTelemetry agent, etc. Values are fixed once the ApplicationReadyEvent has fired.
     */
    get: operations['startupTimings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/demo/security/xss-vulnerable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ⚠️ XSS — VULNERABLE (reflects raw HTML)
     * @description Echoes `name` directly into an HTML page. Try the payload
     *     ```
     *     ?name=&lt;script&gt;alert('XSS')&lt;/script&gt;
     *     ```
     *     **OWASP A07:2021 — Cross-Site Scripting**
     */
    get: operations['xssVulnerable'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/demo/security/xss-safe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ✅ XSS — SAFE (HTML-encoded output)
     * @description HTML-encodes the input using `HtmlUtils.htmlEscape()` before reflecting it. `&lt;script&gt;` becomes `&amp;lt;script&amp;gt;` — displayed as text, not executed.
     */
    get: operations['xssSafe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/demo/security/sqli-vulnerable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ⚠️ SQL Injection — VULNERABLE
     * @description Concatenates user input directly into SQL. Try `?name=Alice' OR '1'='1` to dump all customers. **OWASP A03:2021 — Injection**
     */
    get: operations['sqliVulnerable'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/demo/security/sqli-safe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ✅ SQL Injection — SAFE
     * @description Uses a parameterized query (`?` placeholder). Same input as the vulnerable endpoint — the driver treats it as data, not SQL.
     */
    get: operations['sqliSafe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/demo/security/idor-vulnerable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ⚠️ IDOR — VULNERABLE (no ownership check)
     * @description Returns any customer record by ID with no access control. Enumerate IDs to harvest all data. **OWASP A01:2021 — Broken Object Level Authorization (BOLA/IDOR)**
     */
    get: operations['idorVulnerable'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/demo/security/idor-safe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ✅ IDOR — SAFE (ownership check pattern)
     * @description Shows the correct pattern: `WHERE id = ? AND created_by = :currentUser` + `@PreAuthorize` ownership check.
     */
    get: operations['idorSafe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/demo/security/headers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Security headers metadata
     * @description Returns expected values and explanations for OWASP-recommended security headers: `X-Content-Type-Options`, `X-Frame-Options`, `X-XSS-Protection`, `Referrer-Policy`, `CSP`, `Permissions-Policy`. The frontend compares these expected values against the actual response headers.
     */
    get: operations['headersInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/demo/security/cors-info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * CORS configuration info
     * @description Explains why `allowedOrigins('*') + allowCredentials(true)` is dangerous and how this API is correctly configured.
     */
    get: operations['corsInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/{id}/todos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get todos from JSONPlaceholder (external API)
     * @description Fetches todos for the customer from the external JSONPlaceholder API (https://jsonplaceholder.typicode.com). Decorated with Resilience4j **circuit breaker** + **retry** + fallback (empty list). Demonstrates graceful degradation — never returns 5xx even if the external API is down.
     */
    get: operations['getTodos'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/{id}/enrich': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Enrich customer via Kafka request-reply
     * @description Sends a `CustomerEnrichRequest` to the `customer.request` Kafka topic and **blocks** until the consumer replies on `customer.reply` with a computed `displayName`. Demonstrates synchronous Kafka request-reply (not just fire-and-forget). Returns `504 Gateway Timeout` if no reply arrives within the configured timeout.
     */
    get: operations['enrich'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/{id}/bio': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Generate AI bio (Ollama LLM)
     * @description Calls the local Ollama LLM (llama3.2) via Spring AI to generate a professional bio for the customer. Protected by a Resilience4j **circuit breaker** + **retry** — returns 503 when the circuit is open. Response time: 1–10 s depending on model and hardware.
     */
    get: operations['generateBio'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/{id}/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get audit trail for a customer
     * @description Returns all audit events (CREATE, UPDATE, DELETE, PATCH) for the given customer ID.
     */
    get: operations['getAudit'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Customer summary page (id + name only)
     * @description Lightweight paginated list using a Spring Data **interface projection** — emits `SELECT id, name FROM customer` instead of `SELECT *`. Useful for read-heavy list views where the full DTO is overkill. The `CustomerSummary` interface is resolved by Spring Data JPA without any DTO mapper.
     */
    get: operations['getSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Server-Sent Events stream
     * @description Opens an SSE connection that pushes `customer` events (JSON) whenever a new customer is created. A `ping` event is sent every 30 s to keep the connection alive. **No authentication required** — `EventSource` cannot send custom headers, so this endpoint is `permitAll`.
     */
    get: operations['stream'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/slow-query': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Simulate a slow database query
     * @description Runs `SELECT pg_sleep(N)` to inject artificial latency. The resulting DB span is visible in distributed traces (Grafana Tempo). Max 10 seconds.
     */
    get: operations['slowQuery'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/recent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Recent customers (in-memory buffer)
     * @description Returns the last 10 customers from the in-memory `RecentCustomerBuffer`. No DB query — populated on each `POST /customers`. Demonstrates in-process caching vs DB round-trips.
     */
    get: operations['getRecent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export all customers as CSV
     * @description Streams all customers directly to the response output stream using `StreamingResponseBody` — avoids loading the entire result set into memory. Returns `Content-Disposition: attachment; filename=customers.csv`.
     */
    get: operations['exportCsv'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/cursor': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cursor-based pagination
     * @description Returns customers using `WHERE id > cursor ORDER BY id LIMIT size+1`. Faster than offset-based pagination for large datasets — always an index seek, never a full scan. Pass the last returned `id` as `cursor` in the next request.
     */
    get: operations['getAllCursor'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/aggregate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aggregate stats via virtual threads
     * @description Runs two data-loading tasks in parallel using Java virtual threads (Project Loom). Each task takes ~200 ms — both run concurrently so the total is ~200 ms, not ~400 ms. Visible in traces (two parallel child spans) and in the `customer.aggregate.duration` metric.
     */
    get: operations['aggregate'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chaos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available chaos experiments */
    get: operations['catalog'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List audit events
     * @description Returns a paginated list of security and mutation events. Filter by action (e.g. `LOGIN_FAILED`, `CUSTOMER_CREATED`), username, or time range. Page size is capped at 100.
     */
    get: operations['getAuditEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Request body for creating or updating a customer */
    CreateCustomerRequest: {
      /**
       * @description Full name of the customer
       * @default
       * @example Alice Martin
       */
      name: string;
      /**
       * Format: email
       * @description Unique email address
       * @example alice@example.com
       */
      email: string;
    };
    /** @description Customer resource (API v1) — id, name, email */
    CustomerDto: {
      /**
       * Format: int64
       * @description Unique auto-incremented identifier
       * @example 42
       */
      id?: number;
      /**
       * @description Full name of the customer
       * @default
       * @example Alice Martin
       */
      name: string;
      /**
       * @description Email address (unique per customer)
       * @default
       * @example alice@example.com
       */
      email: string;
    };
    BatchError: {
      /** Format: int32 */
      index?: number;
      name?: string;
      reason?: string;
    };
    BatchImportResult: {
      /** Format: int32 */
      total?: number;
      /** Format: int32 */
      created?: number;
      /** Format: int32 */
      failed?: number;
      customers?: components['schemas']['CustomerDto'][];
      errors?: components['schemas']['BatchError'][];
    };
    RefreshRequest: {
      refreshToken: string;
    };
    LoginRequest: {
      username: string;
      password: string;
    };
    /** @description Partial update request — only provided fields are modified */
    PatchCustomerRequest: {
      /**
       * @description New name (omit to keep current)
       * @default
       * @example Alice Martin
       */
      name: string;
      /**
       * Format: email
       * @description New email (omit to keep current)
       * @example alice@example.com
       */
      email?: string;
    };
    ScheduledJobDto: {
      name?: string;
      /** Format: date-time */
      lockUntil?: string;
      /** Format: date-time */
      lockedAt?: string;
      lockedBy?: string;
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    /** @description Customer resource (API v2) — adds createdAt compared to v1. Request with X-API-Version: 2.0 */
    CustomerDtoV2: {
      /**
       * Format: int64
       * @description Unique auto-incremented identifier
       * @example 42
       */
      id?: number;
      /**
       * @description Full name of the customer
       * @default
       * @example Alice Martin
       */
      name: string;
      /**
       * @description Email address (unique per customer)
       * @default
       * @example alice@example.com
       */
      email: string;
      /**
       * Format: date-time
       * @description UTC timestamp when the customer record was created (ISO-8601)
       * @example 2024-06-01T10:30:00Z
       */
      createdAt?: string;
    };
    PageCustomerDtoV2: {
      /** Format: int32 */
      totalPages?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      first?: boolean;
      last?: boolean;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['CustomerDtoV2'][];
      /** Format: int32 */
      number?: number;
      empty?: boolean;
    };
    PageableObject: {
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      sort?: components['schemas']['SortObject'];
      unpaged?: boolean;
      /** Format: int64 */
      offset?: number;
    };
    SortObject: {
      sorted?: boolean;
      unsorted?: boolean;
      empty?: boolean;
    };
    TodoItem: {
      /** Format: int64 */
      userId?: number;
      /** Format: int64 */
      id?: number;
      title?: string;
      completed?: boolean;
    };
    /** @description Enriched customer — base fields + displayName computed via Kafka request-reply */
    EnrichedCustomerDto: {
      /**
       * Format: int64
       * @description Customer ID
       * @example 42
       */
      id?: number;
      /**
       * @description Customer name
       * @default
       * @example Alice Martin
       */
      name: string;
      /**
       * @description Customer email
       * @default
       * @example alice@example.com
       */
      email: string;
      /**
       * @description Display name computed by the Kafka consumer: 'Name <email>'
       * @default
       * @example Alice Martin <alice@example.com>
       */
      displayName: string;
    };
    AuditEventDto: {
      /** Format: int64 */
      id?: number;
      userName?: string;
      action?: string;
      detail?: string;
      ipAddress?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    CustomerSummary: {
      name?: string;
      /** Format: int64 */
      id?: number;
    };
    PageCustomerSummary: {
      /** Format: int32 */
      totalPages?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      first?: boolean;
      last?: boolean;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['CustomerSummary'][];
      /** Format: int32 */
      number?: number;
      empty?: boolean;
    };
    SseEmitter: {
      /** Format: int64 */
      timeout?: number;
    };
    CursorPageCustomerDto: {
      content?: components['schemas']['CustomerDto'][];
      /** Format: int64 */
      nextCursor?: number;
      hasNext?: boolean;
      /** Format: int32 */
      size?: number;
    };
    AggregatedResponse: {
      customerData?: string;
      stats?: string;
    };
    AuditPage: {
      content?: components['schemas']['AuditEventDto'][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CustomerDto'];
        };
      };
      /** @description Missing or invalid JWT token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description No customer with this ID */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCustomerRequest'];
      };
    };
    responses: {
      /** @description Customer updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CustomerDto'];
        };
      };
      /** @description Validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Missing or invalid JWT token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Lacks ROLE_USER or ROLE_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Customer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Missing or invalid JWT token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Lacks ROLE_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Customer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PatchCustomerRequest'];
      };
    };
    responses: {
      /** @description Customer updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CustomerDto'];
        };
      };
      /** @description Validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Missing or invalid JWT token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Lacks ROLE_USER or ROLE_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Customer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  getAllV2: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
        /** @description Optional search term — filters on name and email */
        search?: string;
      };
      header?: {
        'X-API-Version'?: '2.0' | '1.0' | '1.0.0';
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Page of customers */
      200: {
        headers: {
          /** @description Date after which v1 will be removed */
          Sunset?: unknown[];
          /** @description Marks v1 as deprecated */
          Deprecation?: unknown[];
          /** @description RFC 8288 pagination links */
          Link?: unknown[];
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageCustomerDtoV2'];
        };
      };
      /** @description Missing or invalid JWT token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Rate limit exceeded (100 req/min per IP) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCustomerRequest'];
      };
    };
    responses: {
      /** @description Customer created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CustomerDto'];
        };
      };
      /** @description Validation failed (blank name, invalid email, etc.) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Missing or invalid JWT token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Authenticated but lacks ROLE_USER or ROLE_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Email already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  batchCreate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCustomerRequest'][];
      };
    };
    responses: {
      /** @description Batch result with per-row status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BatchImportResult'];
        };
      };
      /** @description Missing or invalid JWT token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Lacks ROLE_USER or ROLE_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  trigger: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description New `{accessToken, refreshToken}` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': Record<string, never>;
        };
      };
      /** @description Refresh token expired or invalid */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': Record<string, never>;
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Login successful — `{accessToken, refreshToken}` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': Record<string, never>;
        };
      };
      /** @description Invalid credentials — includes `remainingAttempts` */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description IP locked out after too many failures */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  getJobs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of `{name, lockUntil, lockedAt, lockedBy}` rows from the shedlock table. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ScheduledJobDto'][];
        };
      };
      /** @description Missing or invalid JWT token (this endpoint requires authentication) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ScheduledJobDto'][];
        };
      };
    };
  };
  startupTimings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Timings snapshot. `totalBootMs: -1` until the ready event fires. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  xssVulnerable: {
    parameters: {
      query: {
        /**
         * @description Injected HTML/JavaScript
         * @example <img src=x onerror=alert('XSS')>
         */
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/html': string;
        };
      };
    };
  };
  xssSafe: {
    parameters: {
      query: {
        /**
         * @description Input that will be safely HTML-encoded
         * @example <b>Bold</b> & <i>italic</i>
         */
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/html': string;
        };
      };
    };
  };
  sqliVulnerable: {
    parameters: {
      query: {
        /**
         * @description User input injected into SQL
         * @example Alice' OR '1'='1
         */
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  sqliSafe: {
    parameters: {
      query: {
        /**
         * @description Same input, now safely parameterized
         * @example Alice
         */
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  idorVulnerable: {
    parameters: {
      query: {
        /** @description Any customer ID */
        id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  idorSafe: {
    parameters: {
      query: {
        /** @description Customer ID to demonstrate the safe pattern */
        id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  headersInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  corsInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  getTodos: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of todos (may be empty if circuit is open or API is down) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['TodoItem'][];
        };
      };
      /** @description Customer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  enrich: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Enriched customer with displayName */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['EnrichedCustomerDto'];
        };
      };
      /** @description Customer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Kafka consumer did not reply within the timeout */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  generateBio: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bio generated — `{"bio": "..."}` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: string;
          };
        };
      };
      /** @description Customer not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
      /** @description Ollama unavailable or circuit breaker open */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': string;
        };
      };
    };
  };
  getAudit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of audit events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['AuditEventDto'][];
        };
      };
    };
  };
  getSummary: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Page of `{id, name}` projections */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['PageCustomerSummary'];
        };
      };
    };
  };
  stream: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSE stream — content-type: text/event-stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': components['schemas']['SseEmitter'];
        };
      };
    };
  };
  slowQuery: {
    parameters: {
      query?: {
        /** @description Sleep duration in seconds (capped at 10) */
        seconds?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Query completed — returns `{status, duration}` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: string;
          };
        };
      };
    };
  };
  getRecent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Up to 10 most recently created customers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CustomerDto'][];
        };
      };
    };
  };
  exportCsv: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CSV file stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/csv': string;
        };
      };
    };
  };
  getAllCursor: {
    parameters: {
      query?: {
        cursor?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Page with `items`, `nextCursor`, and `hasNext` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CursorPageCustomerDto'];
        };
      };
    };
  };
  aggregate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Aggregated result with count, average name length, and virtual-thread timing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['AggregatedResponse'];
        };
      };
    };
  };
  catalog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  getAuditEvents: {
    parameters: {
      query?: {
        /** @description Zero-based page index */
        page?: string;
        /** @description Page size (max 100) */
        size?: string;
        /**
         * @description Filter by action type, e.g. LOGIN_FAILED, CUSTOMER_CREATED
         * @example LOGIN_FAILED
         */
        action?: string;
        /** @description Filter by username */
        user?: string;
        /**
         * @description Start of time range (ISO-8601)
         * @example 2024-01-01T00:00:00Z
         */
        from?: string;
        /**
         * @description End of time range (ISO-8601)
         * @example 2024-12-31T23:59:59Z
         */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['AuditPage'];
        };
      };
    };
  };
}
