/**
 * QualityComponent — Maven quality report page.
 *
 * Displays a comprehensive build quality report sourced from /actuator/quality:
 * - Test results (Surefire) with per-suite breakdown
 * - Code coverage (JaCoCo) with per-package bars
 * - Static analysis (SpotBugs) bug list
 * - Build metadata (artifact, version, timestamps)
 */
import { Component, DestroyRef, inject, signal, OnInit, OnDestroy } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { HttpClient } from '@angular/common/http';
import { RouterLink } from '@angular/router';
import { EnvService } from '../../../core/env/env.service';
import { AuthService } from '../../../core/auth/auth.service';
import { QcTabPipelineComponent } from './tabs/qc-tab-pipeline.component';
import { QcTabBranchesComponent } from './tabs/qc-tab-branches.component';
import { QcTabRuntimeComponent } from './tabs/qc-tab-runtime.component';
import { QcTabSecurityComponent } from './tabs/qc-tab-security.component';
import { QcTabAnalysisComponent } from './tabs/qc-tab-analysis.component';
import { QcTabBuildComponent } from './tabs/qc-tab-build.component';
import { QcTabMutationComponent } from './tabs/qc-tab-mutation.component';
import { QcTabTestsComponent } from './tabs/qc-tab-tests.component';
import { QcTabOverviewComponent } from './tabs/qc-tab-overview.component';
import { gitWebUrl } from './quality-helpers';
import type { MavenSiteReport, QualityReport } from './quality-types';

@Component({
  selector: 'app-quality',
  standalone: true,
  imports: [
    RouterLink,
    QcTabPipelineComponent,
    QcTabBranchesComponent,
    QcTabRuntimeComponent,
    QcTabSecurityComponent,
    QcTabAnalysisComponent,
    QcTabBuildComponent,
    QcTabMutationComponent,
    QcTabTestsComponent,
    QcTabOverviewComponent,
  ],
  templateUrl: './quality.component.html',
  styleUrl: './quality.component.scss',
})
export class QualityComponent implements OnInit, OnDestroy {
  private readonly http = inject(HttpClient);
  readonly env = inject(EnvService);
  readonly auth = inject(AuthService);
  /**
   * DestroyRef used by `takeUntilDestroyed()` on every HTTP subscribe to
   * stop the post-destroy `signal.set()` callback (Phase 4.1, 2026-04-22).
   */
  private readonly destroyRef = inject(DestroyRef);

  /** Signal: the full quality report loaded from `/actuator/quality`. Null until first load. */
  report = signal<QualityReport | null>(null);

  /** Signal: true while the quality report HTTP request is in flight. */
  loading = signal(false);

  /** Signal: error message if the quality report could not be loaded. */
  error = signal<string | null>(null);

  /** Signal: currently active tab in the Quality page. */
  selectedTab = signal<string>('overview');

  /**
   * Signal: true when the Maven site nginx server (port 8084) responds.
   * Used to show "Detail ↗" links pointing to the full HTML reports.
   * Probed with a HEAD request every 10s until available or the page is destroyed.
   */
  mavenSiteAvailable = signal(false);

  /**
   * Signal: true when the Compodoc nginx server (port 8085) responds.
   * Used to show a "View Compodoc ↗" link in the Overview tab.
   */
  compodocAvailable = signal(false);

  /**
   * Signal: true when the SonarQube instance (port 9000) responds to a HEAD probe.
   * Used to determine whether to show the SonarQube dashboard link as active.
   * SonarQube can take ~2 min to start on first run (Elasticsearch initialization).
   */
  sonarAvailable = signal(false);

  // Polls every 10s until the nginx server responds — cleared once available or on destroy.
  private _mavenSiteRetryTimer: ReturnType<typeof setInterval> | null = null;
  private _compodocRetryTimer: ReturnType<typeof setInterval> | null = null;
  private _sonarRetryTimer: ReturnType<typeof setInterval> | null = null;

  /**
   * List of Maven Site report HTML files shown as "Detail ↗" links in the Overview tab.
   * These are static HTML files generated by `mvn site` and served by nginx on port 8084.
   * The `file` path is appended to `mavenSiteBase` to form the full URL.
   */
  readonly mavenSiteReports: MavenSiteReport[] = [
    { label: 'Project Summary', file: 'index.html', icon: '📋' },
    { label: 'Surefire Tests', file: 'surefire.html', icon: '🧪' },
    { label: 'JaCoCo Coverage', file: 'jacoco/index.html', icon: '📊' },
    { label: 'SpotBugs', file: 'spotbugs.html', icon: '🐛' },
    { label: 'Mutation Testing', file: 'pit-reports/index.html', icon: '🧬' },
    { label: 'CVE Scan', file: 'dependency-check-report.html', icon: '🛡️' },
    { label: 'Javadoc', file: 'apidocs/index.html', icon: '📚' },
  ];

  /**
   * SonarQube projects list URL — shows both mirador (Java) and mirador-ui (Angular).
   * /projects lists all projects; /dashboard?id=X is single-project and would hide mirador-ui.
   */
  get sonarUrl(): string {
    return `${this.env.sonarUrl() ?? 'http://localhost:9000'}/projects`;
  }

  /** Direct SonarQube URL for the backend (Java) project. */
  get sonarBackendUrl(): string {
    return `${this.env.sonarUrl() ?? 'http://localhost:9000'}/dashboard?id=mirador`;
  }

  /** Direct SonarQube URL for the frontend (Angular) project. */
  get sonarFrontendUrl(): string {
    return `${this.env.sonarUrl() ?? 'http://localhost:9000'}/dashboard?id=mirador-ui`;
  }

  /** Base URL of the Maven site: dedicated nginx server if configured, backend fallback. */
  get mavenSiteBase(): string {
    return this.env.mavenSiteUrl() ?? `${this.env.baseUrl()}/maven-site`;
  }

  ngOnInit(): void {
    if (!this.auth.isAdmin()) return; // don't load if not admin
    this.loadReport();
    this.checkMavenSite();
    this.checkCompodoc();
    this.checkSonar();
  }

  ngOnDestroy(): void {
    this.clearMavenSiteRetry();
    this.clearCompodocRetry();
    this.clearSonarRetry();
  }

  loadReport(): void {
    this.loading.set(true);
    this.error.set(null);
    this.http
      .get<QualityReport>(`${this.env.baseUrl()}/actuator/quality`)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (data) => {
          this.report.set(data);
          this.loading.set(false);
        },
        error: (err) => {
          this.error.set(err?.message ?? 'Failed to load quality report');
          this.loading.set(false);
        },
      });
  }

  // Format helpers (severityColor, priorityLabel, nvdUrl, entriesOf,
  // coverageColor, commitUrl) moved to ./quality-helpers.ts under Phase B-5
  // — each tab child imports what it needs locally. The parent only uses
  // gitWebUrl in its template (GitLab button link), exposed below.
  readonly gitWebUrl = gitWebUrl;

  checkMavenSite(): void {
    // Probe the Maven site server (dedicated nginx at mavenSiteUrl, or backend fallback).
    // On failure, starts a 10s retry loop so the tab auto-updates once the server starts
    // (e.g. after running `./run.sh site`) without requiring a full page reload.
    this.clearMavenSiteRetry();
    this.http
      .get(`${this.mavenSiteBase}/index.html`, {
        responseType: 'text',
        observe: 'response',
      })
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.mavenSiteAvailable.set(true);
          this.clearMavenSiteRetry(); // stop polling once the server is reachable
        },
        error: () => {
          this.mavenSiteAvailable.set(false);
          // Retry every 10s — mirrors the Docker API retry in DashboardComponent.
          if (!this._mavenSiteRetryTimer) {
            this._mavenSiteRetryTimer = setInterval(() => this.checkMavenSite(), 10_000);
          }
        },
      });
  }

  private clearMavenSiteRetry(): void {
    if (this._mavenSiteRetryTimer !== null) {
      clearInterval(this._mavenSiteRetryTimer);
      this._mavenSiteRetryTimer = null;
    }
  }

  /** Probes the Compodoc nginx server with 10s retry (same pattern as checkMavenSite). */
  checkCompodoc(): void {
    const url = this.env.compodocUrl();
    if (!url) return;
    this.clearCompodocRetry();
    this.http
      .get(`${url}/index.html`, { responseType: 'text', observe: 'response' })
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.compodocAvailable.set(true);
          this.clearCompodocRetry();
        },
        error: () => {
          this.compodocAvailable.set(false);
          if (!this._compodocRetryTimer) {
            this._compodocRetryTimer = setInterval(() => this.checkCompodoc(), 10_000);
          }
        },
      });
  }

  private clearCompodocRetry(): void {
    if (this._compodocRetryTimer !== null) {
      clearInterval(this._compodocRetryTimer);
      this._compodocRetryTimer = null;
    }
  }

  /**
   * Probes the SonarQube instance with a HEAD request.
   * SonarQube takes ~2 min to start on first run (Elasticsearch init);
   * this retries every 10s so the UI recovers automatically.
   */
  checkSonar(): void {
    const url = this.env.sonarUrl();
    if (!url) return;
    this.clearSonarRetry();
    // Probe /api/system/status — returns 200 JSON regardless of auth
    this.http
      .get(`${url}/api/system/status`, { observe: 'response' })
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.sonarAvailable.set(true);
          this.clearSonarRetry();
        },
        error: () => {
          this.sonarAvailable.set(false);
          if (!this._sonarRetryTimer) {
            this._sonarRetryTimer = setInterval(() => this.checkSonar(), 10_000);
          }
        },
      });
  }

  private clearSonarRetry(): void {
    if (this._sonarRetryTimer !== null) {
      clearInterval(this._sonarRetryTimer);
      this._sonarRetryTimer = null;
    }
  }
}
