/**
 * EnvService — Multi-environment URL management.
 *
 * Manages the active backend environment (Local, Docker, Staging, etc.).
 * All API calls use `baseUrl()` to resolve the target server dynamically.
 * The selected environment is persisted in localStorage and restored on reload.
 *
 * Part of an Angular 21 zoneless app — environment switching is signal-based,
 * so all consumers re-compute automatically without Zone.js.
 */
import { Injectable, signal, computed } from '@angular/core';

/**
 * Descriptor for a backend deployment target.
 * All URL fields are used directly by `ApiService` and `EnvService` computed signals.
 */
export interface Environment {
  /** Human-readable environment name shown in the Settings page selector. */
  name: string;
  /** Base URL of the Spring Boot REST API (e.g., `http://localhost:8080`). */
  baseUrl: string;
  /**
   * URL of the dedicated Maven site static server (nginx port 8084 locally).
   * Separate from the backend so the report server has an independent lifecycle
   * (regenerated daily by CI, not on every backend deploy).
   */
  mavenSiteUrl?: string;
  /**
   * URL of the Compodoc Angular documentation server (nginx port 8085 locally).
   * Generated by `npm run compodoc` in mirador-ui.
   */
  compodocUrl?: string;
}

/**
 * Available backend environments — add entries here for Docker/Staging/Prod.
 * Only `Local` is defined by default; the architecture is designed to support
 * additional entries (Docker, Staging, Production) without code changes.
 */
const ENVIRONMENTS: Environment[] = [
  {
    name: 'Local',
    baseUrl: 'http://localhost:8080',
    // nginx container serving target/site/ — start with `./run.sh site`
    mavenSiteUrl: 'http://localhost:8084',
    // nginx container serving docs/compodoc/ — generate with `npm run compodoc` in mirador-ui
    compodocUrl: 'http://localhost:8085',
  },
];

@Injectable({ providedIn: 'root' })
export class EnvService {
  /** Immutable list of all configured environments, exposed for the Settings UI dropdown. */
  readonly environments = ENVIRONMENTS;

  /** Writable signal holding the currently active environment. Initialized from localStorage. */
  private readonly _current = signal<Environment>(this.restore() ?? ENVIRONMENTS[0]);

  /** Read-only signal for the active environment object. */
  readonly current = this._current.asReadonly();

  /** Computed signal that always returns the active environment's base API URL. */
  readonly baseUrl = computed(() => this._current().baseUrl);

  /** Computed signal for the Maven site URL, or null if not configured for this environment. */
  readonly mavenSiteUrl = computed(() => this._current().mavenSiteUrl ?? null);

  /** Computed signal for the Compodoc URL, or null if not configured for this environment. */
  readonly compodocUrl = computed(() => this._current().compodocUrl ?? null);

  /**
   * Switch to a different backend environment.
   * Persists the selection to localStorage so it survives a page reload.
   *
   * @param env The environment to activate (must be an entry from `environments`).
   */
  select(env: Environment): void {
    this._current.set(env);
    localStorage.setItem('env', JSON.stringify(env));
  }

  /**
   * Restore the previously selected environment from localStorage.
   * Matches by `name` against the `ENVIRONMENTS` list to ensure the in-memory
   * object reference is always from the canonical list (not a stale localStorage copy).
   *
   * @returns The restored environment, or null if none was persisted or the name is unknown.
   */
  private restore(): Environment | null {
    const raw = localStorage.getItem('env');
    if (!raw) return null;
    try {
      const parsed = JSON.parse(raw) as Environment;
      return ENVIRONMENTS.find((e) => e.name === parsed.name) ?? null;
    } catch {
      return null;
    }
  }
}
